[package]
name = "libcgroup_rs"
version = "0.1.0"
authors = ["MeteorCat <meteorcat@live.cn>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "*"
log = "*"